# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import re  # noqa: F401
import io
import warnings

from pydantic.v1 import validate_arguments, ValidationError
from typing import overload, Optional, Union, Awaitable

from datetime import datetime
from pydantic.v1 import Field, StrictInt, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from lusid_workflow.models.create_launcher_request import CreateLauncherRequest
from lusid_workflow.models.deleted_entity_response import DeletedEntityResponse
from lusid_workflow.models.launcher_response import LauncherResponse
from lusid_workflow.models.paged_resource_list_of_launcher_response import PagedResourceListOfLauncherResponse
from lusid_workflow.models.update_launcher_request import UpdateLauncherRequest

from lusid_workflow.api_client import ApiClient
from lusid_workflow.api_response import ApiResponse
from lusid_workflow.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)
from lusid_workflow.extensions.configuration_options import ConfigurationOptions

# ensure templated type usages are imported
from pydantic.v1 import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated

class LaunchersApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @overload
    async def create_launcher(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launcher")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launcher")], create_launcher_request : Annotated[CreateLauncherRequest, Field(description="The data to create a Launcher")], **kwargs) -> LauncherResponse:  # noqa: E501
        ...

    @overload
    def create_launcher(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launcher")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launcher")], create_launcher_request : Annotated[CreateLauncherRequest, Field(description="The data to create a Launcher")], async_req: Optional[bool]=True, **kwargs) -> LauncherResponse:  # noqa: E501
        ...

    @validate_arguments
    def create_launcher(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launcher")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launcher")], create_launcher_request : Annotated[CreateLauncherRequest, Field(description="The data to create a Launcher")], async_req: Optional[bool]=None, **kwargs) -> Union[LauncherResponse, Awaitable[LauncherResponse]]:  # noqa: E501
        """[EXPERIMENTAL] CreateLauncher: Create a new Launcher on a Workflow  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_launcher(scope, code, create_launcher_request, async_req=True)
        >>> result = thread.get()

        :param scope: The scope that identifies the Workflow that owns the Launcher (required)
        :type scope: str
        :param code: The code that identifies the Workflow that owns the Launcher (required)
        :type code: str
        :param create_launcher_request: The data to create a Launcher (required)
        :type create_launcher_request: CreateLauncherRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: LauncherResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the create_launcher_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.create_launcher_with_http_info(scope, code, create_launcher_request, **kwargs)  # noqa: E501

    @validate_arguments
    def create_launcher_with_http_info(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launcher")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launcher")], create_launcher_request : Annotated[CreateLauncherRequest, Field(description="The data to create a Launcher")], **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] CreateLauncher: Create a new Launcher on a Workflow  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_launcher_with_http_info(scope, code, create_launcher_request, async_req=True)
        >>> result = thread.get()

        :param scope: The scope that identifies the Workflow that owns the Launcher (required)
        :type scope: str
        :param code: The code that identifies the Workflow that owns the Launcher (required)
        :type code: str
        :param create_launcher_request: The data to create a Launcher (required)
        :type create_launcher_request: CreateLauncherRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(LauncherResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code',
            'create_launcher_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_launcher" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['create_launcher_request'] is not None:
            _body_params = _params['create_launcher_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '201': "LauncherResponse",
            '400': "LusidValidationProblemDetails",
            '404': "str",
            '409': "str",
        }

        return self.api_client.call_api(
            '/api/workflows/{scope}/{code}/launchers', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def delete_launcher(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launcher")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launcher")], launcher_id : Annotated[StrictStr, Field(..., description="The identifier of the Launcher inside its Workflow")], **kwargs) -> DeletedEntityResponse:  # noqa: E501
        ...

    @overload
    def delete_launcher(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launcher")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launcher")], launcher_id : Annotated[StrictStr, Field(..., description="The identifier of the Launcher inside its Workflow")], async_req: Optional[bool]=True, **kwargs) -> DeletedEntityResponse:  # noqa: E501
        ...

    @validate_arguments
    def delete_launcher(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launcher")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launcher")], launcher_id : Annotated[StrictStr, Field(..., description="The identifier of the Launcher inside its Workflow")], async_req: Optional[bool]=None, **kwargs) -> Union[DeletedEntityResponse, Awaitable[DeletedEntityResponse]]:  # noqa: E501
        """[EXPERIMENTAL] DeleteLauncher: Delete a Launcher of a Workflow  # noqa: E501

        If the Launcher does not exist a failure will be returned  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.delete_launcher(scope, code, launcher_id, async_req=True)
        >>> result = thread.get()

        :param scope: The scope that identifies the Workflow that owns the Launcher (required)
        :type scope: str
        :param code: The code that identifies the Workflow that owns the Launcher (required)
        :type code: str
        :param launcher_id: The identifier of the Launcher inside its Workflow (required)
        :type launcher_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: DeletedEntityResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the delete_launcher_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.delete_launcher_with_http_info(scope, code, launcher_id, **kwargs)  # noqa: E501

    @validate_arguments
    def delete_launcher_with_http_info(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launcher")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launcher")], launcher_id : Annotated[StrictStr, Field(..., description="The identifier of the Launcher inside its Workflow")], **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] DeleteLauncher: Delete a Launcher of a Workflow  # noqa: E501

        If the Launcher does not exist a failure will be returned  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.delete_launcher_with_http_info(scope, code, launcher_id, async_req=True)
        >>> result = thread.get()

        :param scope: The scope that identifies the Workflow that owns the Launcher (required)
        :type scope: str
        :param code: The code that identifies the Workflow that owns the Launcher (required)
        :type code: str
        :param launcher_id: The identifier of the Launcher inside its Workflow (required)
        :type launcher_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(DeletedEntityResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code',
            'launcher_id'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_launcher" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']

        if _params['launcher_id']:
            _path_params['launcherId'] = _params['launcher_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "DeletedEntityResponse",
            '400': "LusidValidationProblemDetails",
            '404': "str",
        }

        return self.api_client.call_api(
            '/api/workflows/{scope}/{code}/launchers/{launcherId}', 'DELETE',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def get_launcher(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launcher")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launcher")], launcher_id : Annotated[StrictStr, Field(..., description="The identifier of the Launcher inside its Workflow")], as_at : Annotated[Optional[datetime], Field(description="The asAt datetime at which to retrieve the Launcher. Defaults to returning the latest             version if not specified.")] = None, **kwargs) -> LauncherResponse:  # noqa: E501
        ...

    @overload
    def get_launcher(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launcher")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launcher")], launcher_id : Annotated[StrictStr, Field(..., description="The identifier of the Launcher inside its Workflow")], as_at : Annotated[Optional[datetime], Field(description="The asAt datetime at which to retrieve the Launcher. Defaults to returning the latest             version if not specified.")] = None, async_req: Optional[bool]=True, **kwargs) -> LauncherResponse:  # noqa: E501
        ...

    @validate_arguments
    def get_launcher(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launcher")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launcher")], launcher_id : Annotated[StrictStr, Field(..., description="The identifier of the Launcher inside its Workflow")], as_at : Annotated[Optional[datetime], Field(description="The asAt datetime at which to retrieve the Launcher. Defaults to returning the latest             version if not specified.")] = None, async_req: Optional[bool]=None, **kwargs) -> Union[LauncherResponse, Awaitable[LauncherResponse]]:  # noqa: E501
        """[EXPERIMENTAL] GetLauncher: Get a Launcher of a Workflow  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_launcher(scope, code, launcher_id, as_at, async_req=True)
        >>> result = thread.get()

        :param scope: The scope that identifies the Workflow that owns the Launcher (required)
        :type scope: str
        :param code: The code that identifies the Workflow that owns the Launcher (required)
        :type code: str
        :param launcher_id: The identifier of the Launcher inside its Workflow (required)
        :type launcher_id: str
        :param as_at: The asAt datetime at which to retrieve the Launcher. Defaults to returning the latest             version if not specified.
        :type as_at: datetime
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: LauncherResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_launcher_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.get_launcher_with_http_info(scope, code, launcher_id, as_at, **kwargs)  # noqa: E501

    @validate_arguments
    def get_launcher_with_http_info(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launcher")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launcher")], launcher_id : Annotated[StrictStr, Field(..., description="The identifier of the Launcher inside its Workflow")], as_at : Annotated[Optional[datetime], Field(description="The asAt datetime at which to retrieve the Launcher. Defaults to returning the latest             version if not specified.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] GetLauncher: Get a Launcher of a Workflow  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_launcher_with_http_info(scope, code, launcher_id, as_at, async_req=True)
        >>> result = thread.get()

        :param scope: The scope that identifies the Workflow that owns the Launcher (required)
        :type scope: str
        :param code: The code that identifies the Workflow that owns the Launcher (required)
        :type code: str
        :param launcher_id: The identifier of the Launcher inside its Workflow (required)
        :type launcher_id: str
        :param as_at: The asAt datetime at which to retrieve the Launcher. Defaults to returning the latest             version if not specified.
        :type as_at: datetime
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(LauncherResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code',
            'launcher_id',
            'as_at'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_launcher" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']

        if _params['launcher_id']:
            _path_params['launcherId'] = _params['launcher_id']


        # process the query parameters
        _query_params = []
        if _params.get('as_at') is not None:  # noqa: E501
            if isinstance(_params['as_at'], datetime):
                _query_params.append(('asAt', _params['as_at'].strftime(self.api_client.configuration.datetime_format)))
            else:
                _query_params.append(('asAt', _params['as_at']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "LauncherResponse",
            '400': "LusidValidationProblemDetails",
            '404': "str",
        }

        return self.api_client.call_api(
            '/api/workflows/{scope}/{code}/launchers/{launcherId}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def list_launchers(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launchers")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launchers")], as_at : Annotated[Optional[datetime], Field(description="The asAt datetime at which to list the Launchers. Defaults to return the latest version             of each Launcher if not specified.")] = None, filter : Annotated[Optional[StrictStr], Field( description="Expression to filter the result set. Read more about filtering results from LUSID here:             https://support.lusid.com/filtering-results-from-lusid.")] = None, sort_by : Annotated[Optional[List[StrictStr]], Field(description="A list of field names to sort by, each suffixed by \" ASC\" or \" DESC\". Defaults to             \"launcherId ASC\" if not specified.")] = None, limit : Annotated[Optional[StrictInt], Field(description="When paginating, limit the number of returned results to this many.")] = None, page : Annotated[Optional[StrictStr], Field( description="The pagination token to use to continue listing Launchers from a previous call to list             Launchers. This value is returned from the previous call. If a pagination token is provided the sortBy,             filter, and asAt fields must not have changed since the original request.")] = None, **kwargs) -> PagedResourceListOfLauncherResponse:  # noqa: E501
        ...

    @overload
    def list_launchers(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launchers")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launchers")], as_at : Annotated[Optional[datetime], Field(description="The asAt datetime at which to list the Launchers. Defaults to return the latest version             of each Launcher if not specified.")] = None, filter : Annotated[Optional[StrictStr], Field( description="Expression to filter the result set. Read more about filtering results from LUSID here:             https://support.lusid.com/filtering-results-from-lusid.")] = None, sort_by : Annotated[Optional[List[StrictStr]], Field(description="A list of field names to sort by, each suffixed by \" ASC\" or \" DESC\". Defaults to             \"launcherId ASC\" if not specified.")] = None, limit : Annotated[Optional[StrictInt], Field(description="When paginating, limit the number of returned results to this many.")] = None, page : Annotated[Optional[StrictStr], Field( description="The pagination token to use to continue listing Launchers from a previous call to list             Launchers. This value is returned from the previous call. If a pagination token is provided the sortBy,             filter, and asAt fields must not have changed since the original request.")] = None, async_req: Optional[bool]=True, **kwargs) -> PagedResourceListOfLauncherResponse:  # noqa: E501
        ...

    @validate_arguments
    def list_launchers(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launchers")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launchers")], as_at : Annotated[Optional[datetime], Field(description="The asAt datetime at which to list the Launchers. Defaults to return the latest version             of each Launcher if not specified.")] = None, filter : Annotated[Optional[StrictStr], Field( description="Expression to filter the result set. Read more about filtering results from LUSID here:             https://support.lusid.com/filtering-results-from-lusid.")] = None, sort_by : Annotated[Optional[List[StrictStr]], Field(description="A list of field names to sort by, each suffixed by \" ASC\" or \" DESC\". Defaults to             \"launcherId ASC\" if not specified.")] = None, limit : Annotated[Optional[StrictInt], Field(description="When paginating, limit the number of returned results to this many.")] = None, page : Annotated[Optional[StrictStr], Field( description="The pagination token to use to continue listing Launchers from a previous call to list             Launchers. This value is returned from the previous call. If a pagination token is provided the sortBy,             filter, and asAt fields must not have changed since the original request.")] = None, async_req: Optional[bool]=None, **kwargs) -> Union[PagedResourceListOfLauncherResponse, Awaitable[PagedResourceListOfLauncherResponse]]:  # noqa: E501
        """[EXPERIMENTAL] ListLaunchers: List the Launchers of a Workflow  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_launchers(scope, code, as_at, filter, sort_by, limit, page, async_req=True)
        >>> result = thread.get()

        :param scope: The scope that identifies the Workflow that owns the Launchers (required)
        :type scope: str
        :param code: The code that identifies the Workflow that owns the Launchers (required)
        :type code: str
        :param as_at: The asAt datetime at which to list the Launchers. Defaults to return the latest version             of each Launcher if not specified.
        :type as_at: datetime
        :param filter: Expression to filter the result set. Read more about filtering results from LUSID here:             https://support.lusid.com/filtering-results-from-lusid.
        :type filter: str
        :param sort_by: A list of field names to sort by, each suffixed by \" ASC\" or \" DESC\". Defaults to             \"launcherId ASC\" if not specified.
        :type sort_by: List[str]
        :param limit: When paginating, limit the number of returned results to this many.
        :type limit: int
        :param page: The pagination token to use to continue listing Launchers from a previous call to list             Launchers. This value is returned from the previous call. If a pagination token is provided the sortBy,             filter, and asAt fields must not have changed since the original request.
        :type page: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: PagedResourceListOfLauncherResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the list_launchers_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.list_launchers_with_http_info(scope, code, as_at, filter, sort_by, limit, page, **kwargs)  # noqa: E501

    @validate_arguments
    def list_launchers_with_http_info(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launchers")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launchers")], as_at : Annotated[Optional[datetime], Field(description="The asAt datetime at which to list the Launchers. Defaults to return the latest version             of each Launcher if not specified.")] = None, filter : Annotated[Optional[StrictStr], Field( description="Expression to filter the result set. Read more about filtering results from LUSID here:             https://support.lusid.com/filtering-results-from-lusid.")] = None, sort_by : Annotated[Optional[List[StrictStr]], Field(description="A list of field names to sort by, each suffixed by \" ASC\" or \" DESC\". Defaults to             \"launcherId ASC\" if not specified.")] = None, limit : Annotated[Optional[StrictInt], Field(description="When paginating, limit the number of returned results to this many.")] = None, page : Annotated[Optional[StrictStr], Field( description="The pagination token to use to continue listing Launchers from a previous call to list             Launchers. This value is returned from the previous call. If a pagination token is provided the sortBy,             filter, and asAt fields must not have changed since the original request.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] ListLaunchers: List the Launchers of a Workflow  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_launchers_with_http_info(scope, code, as_at, filter, sort_by, limit, page, async_req=True)
        >>> result = thread.get()

        :param scope: The scope that identifies the Workflow that owns the Launchers (required)
        :type scope: str
        :param code: The code that identifies the Workflow that owns the Launchers (required)
        :type code: str
        :param as_at: The asAt datetime at which to list the Launchers. Defaults to return the latest version             of each Launcher if not specified.
        :type as_at: datetime
        :param filter: Expression to filter the result set. Read more about filtering results from LUSID here:             https://support.lusid.com/filtering-results-from-lusid.
        :type filter: str
        :param sort_by: A list of field names to sort by, each suffixed by \" ASC\" or \" DESC\". Defaults to             \"launcherId ASC\" if not specified.
        :type sort_by: List[str]
        :param limit: When paginating, limit the number of returned results to this many.
        :type limit: int
        :param page: The pagination token to use to continue listing Launchers from a previous call to list             Launchers. This value is returned from the previous call. If a pagination token is provided the sortBy,             filter, and asAt fields must not have changed since the original request.
        :type page: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(PagedResourceListOfLauncherResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code',
            'as_at',
            'filter',
            'sort_by',
            'limit',
            'page'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_launchers" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']


        # process the query parameters
        _query_params = []
        if _params.get('as_at') is not None:  # noqa: E501
            if isinstance(_params['as_at'], datetime):
                _query_params.append(('asAt', _params['as_at'].strftime(self.api_client.configuration.datetime_format)))
            else:
                _query_params.append(('asAt', _params['as_at']))

        if _params.get('filter') is not None:  # noqa: E501
            _query_params.append(('filter', _params['filter']))

        if _params.get('sort_by') is not None:  # noqa: E501
            _query_params.append(('sortBy', _params['sort_by']))
            _collection_formats['sortBy'] = 'multi'

        if _params.get('limit') is not None:  # noqa: E501
            _query_params.append(('limit', _params['limit']))

        if _params.get('page') is not None:  # noqa: E501
            _query_params.append(('page', _params['page']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "PagedResourceListOfLauncherResponse",
            '400': "LusidValidationProblemDetails",
            '404': "str",
        }

        return self.api_client.call_api(
            '/api/workflows/{scope}/{code}/launchers', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def update_launcher(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launcher")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launcher")], launcher_id : Annotated[StrictStr, Field(..., description="The identifier of the Launcher inside its Workflow")], update_launcher_request : Annotated[UpdateLauncherRequest, Field(description="The data to update a Launcher")], **kwargs) -> LauncherResponse:  # noqa: E501
        ...

    @overload
    def update_launcher(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launcher")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launcher")], launcher_id : Annotated[StrictStr, Field(..., description="The identifier of the Launcher inside its Workflow")], update_launcher_request : Annotated[UpdateLauncherRequest, Field(description="The data to update a Launcher")], async_req: Optional[bool]=True, **kwargs) -> LauncherResponse:  # noqa: E501
        ...

    @validate_arguments
    def update_launcher(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launcher")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launcher")], launcher_id : Annotated[StrictStr, Field(..., description="The identifier of the Launcher inside its Workflow")], update_launcher_request : Annotated[UpdateLauncherRequest, Field(description="The data to update a Launcher")], async_req: Optional[bool]=None, **kwargs) -> Union[LauncherResponse, Awaitable[LauncherResponse]]:  # noqa: E501
        """[EXPERIMENTAL] UpdateLauncher: Update an existing Launcher of a Workflow  # noqa: E501

        The type of a Launcher cannot be changed  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_launcher(scope, code, launcher_id, update_launcher_request, async_req=True)
        >>> result = thread.get()

        :param scope: The scope that identifies the Workflow that owns the Launcher (required)
        :type scope: str
        :param code: The code that identifies the Workflow that owns the Launcher (required)
        :type code: str
        :param launcher_id: The identifier of the Launcher inside its Workflow (required)
        :type launcher_id: str
        :param update_launcher_request: The data to update a Launcher (required)
        :type update_launcher_request: UpdateLauncherRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: LauncherResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the update_launcher_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.update_launcher_with_http_info(scope, code, launcher_id, update_launcher_request, **kwargs)  # noqa: E501

    @validate_arguments
    def update_launcher_with_http_info(self, scope : Annotated[StrictStr, Field(..., description="The scope that identifies the Workflow that owns the Launcher")], code : Annotated[StrictStr, Field(..., description="The code that identifies the Workflow that owns the Launcher")], launcher_id : Annotated[StrictStr, Field(..., description="The identifier of the Launcher inside its Workflow")], update_launcher_request : Annotated[UpdateLauncherRequest, Field(description="The data to update a Launcher")], **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] UpdateLauncher: Update an existing Launcher of a Workflow  # noqa: E501

        The type of a Launcher cannot be changed  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_launcher_with_http_info(scope, code, launcher_id, update_launcher_request, async_req=True)
        >>> result = thread.get()

        :param scope: The scope that identifies the Workflow that owns the Launcher (required)
        :type scope: str
        :param code: The code that identifies the Workflow that owns the Launcher (required)
        :type code: str
        :param launcher_id: The identifier of the Launcher inside its Workflow (required)
        :type launcher_id: str
        :param update_launcher_request: The data to update a Launcher (required)
        :type update_launcher_request: UpdateLauncherRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(LauncherResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code',
            'launcher_id',
            'update_launcher_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_launcher" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']

        if _params['launcher_id']:
            _path_params['launcherId'] = _params['launcher_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['update_launcher_request'] is not None:
            _body_params = _params['update_launcher_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "LauncherResponse",
            '400': "LusidValidationProblemDetails",
            '404': "str",
        }

        return self.api_client.call_api(
            '/api/workflows/{scope}/{code}/launchers/{launcherId}', 'PUT',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
