# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid_workflow.models.calendar_reference import CalendarReference

class CalendarContext(BaseModel):
    """
    A named time zone and set of holiday calendars.  # noqa: E501
    """
    name:  StrictStr = Field(...,alias="name", description="The name the schedule and the date and time adjustments use to name this context") 
    time_zone:  StrictStr = Field(...,alias="timeZone", description="The time zone to use. A TZ identifier, for example \"Europe/London\"") 
    holiday_calendars: Optional[List[CalendarReference]] = Field(default=None, description="The holiday calendars that decide which dates are business days in this context", alias="holidayCalendars")
    __properties = ["name", "timeZone", "holidayCalendars"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CalendarContext:
        """Create an instance of CalendarContext from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in holiday_calendars (list)
        _items = []
        if self.holiday_calendars:
            for _item in self.holiday_calendars:
                if _item:
                    _items.append(_item.to_dict())
            _dict['holidayCalendars'] = _items
        # set to None if holiday_calendars (nullable) is None
        # and __fields_set__ contains the field
        if self.holiday_calendars is None and "holiday_calendars" in self.__fields_set__:
            _dict['holidayCalendars'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CalendarContext:
        """Create an instance of CalendarContext from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CalendarContext.parse_obj(obj)

        _obj = CalendarContext.parse_obj({
            "name": obj.get("name"),
            "time_zone": obj.get("timeZone"),
            "holiday_calendars": [CalendarReference.from_dict(_item) for _item in obj.get("holidayCalendars")] if obj.get("holidayCalendars") is not None else None
        })
        return _obj

CalendarContext.update_forward_refs()
