# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid_workflow.models.date_adjustment import DateAdjustment
from lusid_workflow.models.time_adjustment import TimeAdjustment

class DateTimeAdjustment(BaseModel):
    """
    A change applied to the date and the time of a source value, in a named calendar context.              At least one of Finbourne.Workflow.WebApi.Common.Dto.Json.Launchers.DateTimeAdjustment.DateAdjustment or Finbourne.Workflow.WebApi.Common.Dto.Json.Launchers.DateTimeAdjustment.TimeAdjustment must be given  # noqa: E501
    """
    calendar_context:  Optional[StrictStr] = Field(None,alias="calendarContext", description="The name of the calendar context this change happens in, which must be one the Launcher declares. When it is left out a Schedule Launcher uses the context of its schedule") 
    date_adjustment: Optional[DateAdjustment] = Field(default=None, alias="dateAdjustment")
    time_adjustment: Optional[TimeAdjustment] = Field(default=None, alias="timeAdjustment")
    __properties = ["calendarContext", "dateAdjustment", "timeAdjustment"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DateTimeAdjustment:
        """Create an instance of DateTimeAdjustment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of date_adjustment
        if self.date_adjustment:
            _dict['dateAdjustment'] = self.date_adjustment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of time_adjustment
        if self.time_adjustment:
            _dict['timeAdjustment'] = self.time_adjustment.to_dict()
        # set to None if calendar_context (nullable) is None
        # and __fields_set__ contains the field
        if self.calendar_context is None and "calendar_context" in self.__fields_set__:
            _dict['calendarContext'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DateTimeAdjustment:
        """Create an instance of DateTimeAdjustment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DateTimeAdjustment.parse_obj(obj)

        _obj = DateTimeAdjustment.parse_obj({
            "calendar_context": obj.get("calendarContext"),
            "date_adjustment": DateAdjustment.from_dict(obj.get("dateAdjustment")) if obj.get("dateAdjustment") is not None else None,
            "time_adjustment": TimeAdjustment.from_dict(obj.get("timeAdjustment")) if obj.get("timeAdjustment") is not None else None
        })
        return _obj

DateTimeAdjustment.update_forward_refs()
