# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid_workflow.models.correlation_id_mapping import CorrelationIdMapping
from lusid_workflow.models.event_task_field_mapping import EventTaskFieldMapping
from lusid_workflow.models.launcher_event_matching_pattern import LauncherEventMatchingPattern
from lusid_workflow.models.launcher_mapping import LauncherMapping

class EventLauncherDetails(BaseModel):
    """
    A Launcher that starts a run of its Workflow when a matching platform event arrives, and can fill fields and correlation IDs of the root task from that event  # noqa: E501
    """
    launcher_type:  StrictStr = Field(...,alias="launcherType") 
    event_matching_pattern: LauncherEventMatchingPattern = Field(alias="eventMatchingPattern")
    map_task_fields: Optional[Dict[str, EventTaskFieldMapping]] = Field(default=None, description="Fields of the root task filled from the event, keyed by the field name on the root task definition", alias="mapTaskFields")
    map_correlation_ids: Optional[List[CorrelationIdMapping]] = Field(default=None, description="Correlation IDs of the root task filled from the event", alias="mapCorrelationIds")
    run_as_user_id: LauncherMapping = Field(alias="runAsUserId")
    set_task_fields: Optional[Dict[str, Any]] = Field(default=None, description="Fields of the root task set to a fixed value, keyed by the field name on the root task definition", alias="setTaskFields")
    set_correlation_ids: Optional[List[StrictStr]] = Field(default=None, description="Correlation IDs put on the root task as given", alias="setCorrelationIds")
    initial_trigger:  Optional[StrictStr] = Field(None,alias="initialTrigger", description="The trigger given to the root task once it is made and all of its fields are filled. When it is left out the root task is left in its initial state") 
    __properties = ["launcherType", "eventMatchingPattern", "mapTaskFields", "mapCorrelationIds", "runAsUserId", "setTaskFields", "setCorrelationIds", "initialTrigger"]

    @validator('launcher_type')
    def launcher_type_validate_enum(cls, value):
        """Validates the enum"""

        # Finbourne removed enum validation on all models except the
        # oneOf-discriminator case: each oneOf variant declares a
        # discriminator field (e.g. `type`, `launcherType`) whose enum has
        # exactly one allowable value, which pydantic uses to route the
        # union. We detect that shape here (single allowable value) — no
        # manual class list, no hard-coded discriminator name.

        _allowed = ['Event']
        if len(_allowed) != 1:
            return value
        if value not in _allowed:
            raise ValueError(f"must be one of enum values {_allowed}")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EventLauncherDetails:
        """Create an instance of EventLauncherDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of event_matching_pattern
        if self.event_matching_pattern:
            _dict['eventMatchingPattern'] = self.event_matching_pattern.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in map_task_fields (dict)
        _field_dict = {}
        if self.map_task_fields:
            for _key in self.map_task_fields:
                if self.map_task_fields[_key]:
                    _field_dict[_key] = self.map_task_fields[_key].to_dict()
            _dict['mapTaskFields'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in map_correlation_ids (list)
        _items = []
        if self.map_correlation_ids:
            for _item in self.map_correlation_ids:
                if _item:
                    _items.append(_item.to_dict())
            _dict['mapCorrelationIds'] = _items
        # override the default output from pydantic by calling `to_dict()` of run_as_user_id
        if self.run_as_user_id:
            _dict['runAsUserId'] = self.run_as_user_id.to_dict()
        # set to None if map_task_fields (nullable) is None
        # and __fields_set__ contains the field
        if self.map_task_fields is None and "map_task_fields" in self.__fields_set__:
            _dict['mapTaskFields'] = None

        # set to None if map_correlation_ids (nullable) is None
        # and __fields_set__ contains the field
        if self.map_correlation_ids is None and "map_correlation_ids" in self.__fields_set__:
            _dict['mapCorrelationIds'] = None

        # set to None if set_task_fields (nullable) is None
        # and __fields_set__ contains the field
        if self.set_task_fields is None and "set_task_fields" in self.__fields_set__:
            _dict['setTaskFields'] = None

        # set to None if set_correlation_ids (nullable) is None
        # and __fields_set__ contains the field
        if self.set_correlation_ids is None and "set_correlation_ids" in self.__fields_set__:
            _dict['setCorrelationIds'] = None

        # set to None if initial_trigger (nullable) is None
        # and __fields_set__ contains the field
        if self.initial_trigger is None and "initial_trigger" in self.__fields_set__:
            _dict['initialTrigger'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EventLauncherDetails:
        """Create an instance of EventLauncherDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EventLauncherDetails.parse_obj(obj)

        _obj = EventLauncherDetails.parse_obj({
            "launcher_type": obj.get("launcherType"),
            "event_matching_pattern": LauncherEventMatchingPattern.from_dict(obj.get("eventMatchingPattern")) if obj.get("eventMatchingPattern") is not None else None,
            "map_task_fields": dict(
                (_k, EventTaskFieldMapping.from_dict(_v))
                for _k, _v in obj.get("mapTaskFields").items()
            )
            if obj.get("mapTaskFields") is not None
            else None,
            "map_correlation_ids": [CorrelationIdMapping.from_dict(_item) for _item in obj.get("mapCorrelationIds")] if obj.get("mapCorrelationIds") is not None else None,
            "run_as_user_id": LauncherMapping.from_dict(obj.get("runAsUserId")) if obj.get("runAsUserId") is not None else None,
            "set_task_fields": obj.get("setTaskFields"),
            "set_correlation_ids": obj.get("setCorrelationIds"),
            "initial_trigger": obj.get("initialTrigger")
        })
        return _obj

EventLauncherDetails.update_forward_refs()
