# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class ExistingTasksRecurringConfiguration(BaseModel):
    """
    Behaviour applied to an existing (non-terminal) child task whose stacking key matches one or more new child task candidates  # noqa: E501
    """
    increment_as_at_modified: Optional[StrictBool] = Field(default=None, description="When true, the existing task's asAtModified is incremented even if no other change (Trigger or MergeFields) is applied", alias="incrementAsAtModified")
    trigger:  Optional[StrictStr] = Field(None,alias="trigger", description="The existing task receives this trigger") 
    merge_fields: Optional[List[StrictStr]] = Field(default=None, description="The named fields on the existing task are updated with the values from the latest run. Only applies where the new-to-existing stacking key cardinality is one-to-one or one-to-many; unspecified fields are untouched. Data will be merged in even if these fields are in a read-only state.", alias="mergeFields")
    __properties = ["incrementAsAtModified", "trigger", "mergeFields"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ExistingTasksRecurringConfiguration:
        """Create an instance of ExistingTasksRecurringConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if trigger (nullable) is None
        # and __fields_set__ contains the field
        if self.trigger is None and "trigger" in self.__fields_set__:
            _dict['trigger'] = None

        # set to None if merge_fields (nullable) is None
        # and __fields_set__ contains the field
        if self.merge_fields is None and "merge_fields" in self.__fields_set__:
            _dict['mergeFields'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ExistingTasksRecurringConfiguration:
        """Create an instance of ExistingTasksRecurringConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ExistingTasksRecurringConfiguration.parse_obj(obj)

        _obj = ExistingTasksRecurringConfiguration.parse_obj({
            "increment_as_at_modified": obj.get("incrementAsAtModified"),
            "trigger": obj.get("trigger"),
            "merge_fields": obj.get("mergeFields")
        })
        return _obj

ExistingTasksRecurringConfiguration.update_forward_refs()
