# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class LauncherSummaries(BaseModel):
    """
    Sentences that say what a Launcher does, meant to be shown to a person.              These are rendered on read from the stored Launcher details. They are never stored and never accepted on a write, so the same Launcher always reads back the same summaries  # noqa: E501
    """
    schedule:  Optional[StrictStr] = Field(None,alias="schedule", description="A sentence that says when the Launcher starts a run, for example \"Weekly on Mon at 09:00, rolled forward to the next business day\".              Null for an Event Launcher, which has no schedule") 
    fields: Optional[Dict[str, Optional[StrictStr]]] = Field(default=None, description="A sentence for each field of the root task the Launcher fills, keyed by the field name on the root task definition. Empty when the Launcher fills no fields")
    __properties = ["schedule", "fields"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LauncherSummaries:
        """Create an instance of LauncherSummaries from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if schedule (nullable) is None
        # and __fields_set__ contains the field
        if self.schedule is None and "schedule" in self.__fields_set__:
            _dict['schedule'] = None

        # set to None if fields (nullable) is None
        # and __fields_set__ contains the field
        if self.fields is None and "fields" in self.__fields_set__:
            _dict['fields'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LauncherSummaries:
        """Create an instance of LauncherSummaries from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LauncherSummaries.parse_obj(obj)

        _obj = LauncherSummaries.parse_obj({
            "schedule": obj.get("schedule"),
            "fields": obj.get("fields")
        })
        return _obj

LauncherSummaries.update_forward_refs()
