# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid_workflow.models.versioned_task_definition_id import VersionedTaskDefinitionId

class LauncherEdge(BaseModel):
    """
    Represents the relationship between a Launcher of a Workflow and the Task Definition it starts a run of  # noqa: E501
    """
    launcher_id:  Optional[StrictStr] = Field(None,alias="launcherId", description="The identifier of the Launcher inside its Workflow") 
    target_task_definition: Optional[VersionedTaskDefinitionId] = Field(default=None, alias="targetTaskDefinition")
    __properties = ["launcherId", "targetTaskDefinition"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LauncherEdge:
        """Create an instance of LauncherEdge from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of target_task_definition
        if self.target_task_definition:
            _dict['targetTaskDefinition'] = self.target_task_definition.to_dict()
        # set to None if launcher_id (nullable) is None
        # and __fields_set__ contains the field
        if self.launcher_id is None and "launcher_id" in self.__fields_set__:
            _dict['launcherId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LauncherEdge:
        """Create an instance of LauncherEdge from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LauncherEdge.parse_obj(obj)

        _obj = LauncherEdge.parse_obj({
            "launcher_id": obj.get("launcherId"),
            "target_task_definition": VersionedTaskDefinitionId.from_dict(obj.get("targetTaskDefinition")) if obj.get("targetTaskDefinition") is not None else None
        })
        return _obj

LauncherEdge.update_forward_refs()
