# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid_workflow.models.launcher_details_response import LauncherDetailsResponse
from lusid_workflow.models.launcher_summaries import LauncherSummaries
from lusid_workflow.models.resource_id import ResourceId
from lusid_workflow.models.version_info import VersionInfo

class LauncherResponse(BaseModel):
    """
    A Launcher, which starts a run of one Workflow either at the times a schedule gives or when a matching event arrives  # noqa: E501
    """
    workflow_id: ResourceId = Field(alias="workflowId")
    launcher_id:  StrictStr = Field(...,alias="launcherId", description="The identifier of this Launcher inside its Workflow") 
    display_name:  StrictStr = Field(...,alias="displayName", description="Human-readable name") 
    description:  Optional[StrictStr] = Field(None,alias="description", description="Human-readable description") 
    status:  StrictStr = Field(...,alias="status", description="The current status of the Launcher. One of - Active, Inactive") 
    launcher_details: LauncherDetailsResponse = Field(alias="launcherDetails")
    summaries: Optional[LauncherSummaries] = None
    version: Optional[VersionInfo] = None
    __properties = ["workflowId", "launcherId", "displayName", "description", "status", "launcherDetails", "summaries", "version"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LauncherResponse:
        """Create an instance of LauncherResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of workflow_id
        if self.workflow_id:
            _dict['workflowId'] = self.workflow_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of launcher_details
        if self.launcher_details:
            _dict['launcherDetails'] = self.launcher_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of summaries
        if self.summaries:
            _dict['summaries'] = self.summaries.to_dict()
        # override the default output from pydantic by calling `to_dict()` of version
        if self.version:
            _dict['version'] = self.version.to_dict()
        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LauncherResponse:
        """Create an instance of LauncherResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LauncherResponse.parse_obj(obj)

        _obj = LauncherResponse.parse_obj({
            "workflow_id": ResourceId.from_dict(obj.get("workflowId")) if obj.get("workflowId") is not None else None,
            "launcher_id": obj.get("launcherId"),
            "display_name": obj.get("displayName"),
            "description": obj.get("description"),
            "status": obj.get("status"),
            "launcher_details": LauncherDetailsResponse.from_dict(obj.get("launcherDetails")) if obj.get("launcherDetails") is not None else None,
            "summaries": LauncherSummaries.from_dict(obj.get("summaries")) if obj.get("summaries") is not None else None,
            "version": VersionInfo.from_dict(obj.get("version")) if obj.get("version") is not None else None
        })
        return _obj

LauncherResponse.update_forward_refs()
