# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid_workflow.models.resource_id import ResourceId
from lusid_workflow.models.results_not_recurring_configuration import ResultsNotRecurringConfiguration
from lusid_workflow.models.results_recurring_configuration import ResultsRecurringConfiguration

class ReRunConfiguration(BaseModel):
    """
    Defines how re-run results for a given (child) TaskDefinitionId should be reconciled against existing (non-terminal) child tasks of the same parent Task instance.  # noqa: E501
    """
    task_definition_id: ResourceId = Field(alias="taskDefinitionId")
    results_recurring: ResultsRecurringConfiguration = Field(alias="resultsRecurring")
    results_not_recurring: ResultsNotRecurringConfiguration = Field(alias="resultsNotRecurring")
    __properties = ["taskDefinitionId", "resultsRecurring", "resultsNotRecurring"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ReRunConfiguration:
        """Create an instance of ReRunConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of task_definition_id
        if self.task_definition_id:
            _dict['taskDefinitionId'] = self.task_definition_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of results_recurring
        if self.results_recurring:
            _dict['resultsRecurring'] = self.results_recurring.to_dict()
        # override the default output from pydantic by calling `to_dict()` of results_not_recurring
        if self.results_not_recurring:
            _dict['resultsNotRecurring'] = self.results_not_recurring.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ReRunConfiguration:
        """Create an instance of ReRunConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ReRunConfiguration.parse_obj(obj)

        _obj = ReRunConfiguration.parse_obj({
            "task_definition_id": ResourceId.from_dict(obj.get("taskDefinitionId")) if obj.get("taskDefinitionId") is not None else None,
            "results_recurring": ResultsRecurringConfiguration.from_dict(obj.get("resultsRecurring")) if obj.get("resultsRecurring") is not None else None,
            "results_not_recurring": ResultsNotRecurringConfiguration.from_dict(obj.get("resultsNotRecurring")) if obj.get("resultsNotRecurring") is not None else None
        })
        return _obj

ReRunConfiguration.update_forward_refs()
