# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid_workflow.models.date_time_adjustment import DateTimeAdjustment

class ScheduleTaskFieldMapping(BaseModel):
    """
    How a Schedule Launcher fills one field of the root task from the instant the schedule fired  # noqa: E501
    """
    map_from:  StrictStr = Field(...,alias="mapFrom", description="The value the field is taken from. One of - ScheduledTime") 
    date_time_adjustment: Optional[DateTimeAdjustment] = Field(default=None, alias="dateTimeAdjustment")
    __properties = ["mapFrom", "dateTimeAdjustment"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ScheduleTaskFieldMapping:
        """Create an instance of ScheduleTaskFieldMapping from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of date_time_adjustment
        if self.date_time_adjustment:
            _dict['dateTimeAdjustment'] = self.date_time_adjustment.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ScheduleTaskFieldMapping:
        """Create an instance of ScheduleTaskFieldMapping from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ScheduleTaskFieldMapping.parse_obj(obj)

        _obj = ScheduleTaskFieldMapping.parse_obj({
            "map_from": obj.get("mapFrom"),
            "date_time_adjustment": DateTimeAdjustment.from_dict(obj.get("dateTimeAdjustment")) if obj.get("dateTimeAdjustment") is not None else None
        })
        return _obj

ScheduleTaskFieldMapping.update_forward_refs()
