# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid_workflow.models.calendar_context import CalendarContext
from lusid_workflow.models.launcher_mapping import LauncherMapping
from lusid_workflow.models.launcher_schedule import LauncherSchedule
from lusid_workflow.models.schedule_task_field_mapping import ScheduleTaskFieldMapping

class ScheduleLauncherDetails(BaseModel):
    """
    A Launcher that starts a run of its Workflow at the times a recurrence pattern gives, and can fill date and time fields of the root task from the instant it fired  # noqa: E501
    """
    launcher_type:  StrictStr = Field(...,alias="launcherType") 
    schedule: LauncherSchedule
    calendar_contexts: Optional[List[CalendarContext]] = Field(default=None, description="The named time zones and holiday calendars this Launcher works in.              Only a Schedule Launcher works in a calendar context", alias="calendarContexts")
    map_task_fields: Optional[Dict[str, ScheduleTaskFieldMapping]] = Field(default=None, description="Fields of the root task filled from the instant the schedule fired, keyed by the field name on the root task definition", alias="mapTaskFields")
    run_as_user_id: LauncherMapping = Field(alias="runAsUserId")
    set_task_fields: Optional[Dict[str, Any]] = Field(default=None, description="Fields of the root task set to a fixed value, keyed by the field name on the root task definition", alias="setTaskFields")
    set_correlation_ids: Optional[List[StrictStr]] = Field(default=None, description="Correlation IDs put on the root task as given", alias="setCorrelationIds")
    initial_trigger:  Optional[StrictStr] = Field(None,alias="initialTrigger", description="The trigger given to the root task once it is made and all of its fields are filled. When it is left out the root task is left in its initial state") 
    __properties = ["launcherType", "schedule", "calendarContexts", "mapTaskFields", "runAsUserId", "setTaskFields", "setCorrelationIds", "initialTrigger"]

    @validator('launcher_type')
    def launcher_type_validate_enum(cls, value):
        """Validates the enum"""

        # Finbourne removed enum validation on all models except the
        # oneOf-discriminator case: each oneOf variant declares a
        # discriminator field (e.g. `type`, `launcherType`) whose enum has
        # exactly one allowable value, which pydantic uses to route the
        # union. We detect that shape here (single allowable value) — no
        # manual class list, no hard-coded discriminator name.

        _allowed = ['Schedule']
        if len(_allowed) != 1:
            return value
        if value not in _allowed:
            raise ValueError(f"must be one of enum values {_allowed}")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ScheduleLauncherDetails:
        """Create an instance of ScheduleLauncherDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of schedule
        if self.schedule:
            _dict['schedule'] = self.schedule.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in calendar_contexts (list)
        _items = []
        if self.calendar_contexts:
            for _item in self.calendar_contexts:
                if _item:
                    _items.append(_item.to_dict())
            _dict['calendarContexts'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in map_task_fields (dict)
        _field_dict = {}
        if self.map_task_fields:
            for _key in self.map_task_fields:
                if self.map_task_fields[_key]:
                    _field_dict[_key] = self.map_task_fields[_key].to_dict()
            _dict['mapTaskFields'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of run_as_user_id
        if self.run_as_user_id:
            _dict['runAsUserId'] = self.run_as_user_id.to_dict()
        # set to None if calendar_contexts (nullable) is None
        # and __fields_set__ contains the field
        if self.calendar_contexts is None and "calendar_contexts" in self.__fields_set__:
            _dict['calendarContexts'] = None

        # set to None if map_task_fields (nullable) is None
        # and __fields_set__ contains the field
        if self.map_task_fields is None and "map_task_fields" in self.__fields_set__:
            _dict['mapTaskFields'] = None

        # set to None if set_task_fields (nullable) is None
        # and __fields_set__ contains the field
        if self.set_task_fields is None and "set_task_fields" in self.__fields_set__:
            _dict['setTaskFields'] = None

        # set to None if set_correlation_ids (nullable) is None
        # and __fields_set__ contains the field
        if self.set_correlation_ids is None and "set_correlation_ids" in self.__fields_set__:
            _dict['setCorrelationIds'] = None

        # set to None if initial_trigger (nullable) is None
        # and __fields_set__ contains the field
        if self.initial_trigger is None and "initial_trigger" in self.__fields_set__:
            _dict['initialTrigger'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ScheduleLauncherDetails:
        """Create an instance of ScheduleLauncherDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ScheduleLauncherDetails.parse_obj(obj)

        _obj = ScheduleLauncherDetails.parse_obj({
            "launcher_type": obj.get("launcherType"),
            "schedule": LauncherSchedule.from_dict(obj.get("schedule")) if obj.get("schedule") is not None else None,
            "calendar_contexts": [CalendarContext.from_dict(_item) for _item in obj.get("calendarContexts")] if obj.get("calendarContexts") is not None else None,
            "map_task_fields": dict(
                (_k, ScheduleTaskFieldMapping.from_dict(_v))
                for _k, _v in obj.get("mapTaskFields").items()
            )
            if obj.get("mapTaskFields") is not None
            else None,
            "run_as_user_id": LauncherMapping.from_dict(obj.get("runAsUserId")) if obj.get("runAsUserId") is not None else None,
            "set_task_fields": obj.get("setTaskFields"),
            "set_correlation_ids": obj.get("setCorrelationIds"),
            "initial_trigger": obj.get("initialTrigger")
        })
        return _obj

ScheduleLauncherDetails.update_forward_refs()
