# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid_workflow.models.resource_id import ResourceId

class VersionedTaskDefinitionId(BaseModel):
    """
    A Task Definition Id with an optional asAt timestamp identifying a specific version  # noqa: E501
    """
    task_definition_id: Optional[ResourceId] = Field(default=None, alias="taskDefinitionId")
    task_definition_as_at: Optional[datetime] = Field(default=None, description="The asAt time of this version of the Task Definition. Null means the latest version.", alias="taskDefinitionAsAt")
    __properties = ["taskDefinitionId", "taskDefinitionAsAt"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VersionedTaskDefinitionId:
        """Create an instance of VersionedTaskDefinitionId from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of task_definition_id
        if self.task_definition_id:
            _dict['taskDefinitionId'] = self.task_definition_id.to_dict()
        # set to None if task_definition_as_at (nullable) is None
        # and __fields_set__ contains the field
        if self.task_definition_as_at is None and "task_definition_as_at" in self.__fields_set__:
            _dict['taskDefinitionAsAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VersionedTaskDefinitionId:
        """Create an instance of VersionedTaskDefinitionId from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VersionedTaskDefinitionId.parse_obj(obj)

        _obj = VersionedTaskDefinitionId.parse_obj({
            "task_definition_id": ResourceId.from_dict(obj.get("taskDefinitionId")) if obj.get("taskDefinitionId") is not None else None,
            "task_definition_as_at": obj.get("taskDefinitionAsAt")
        })
        return _obj

VersionedTaskDefinitionId.update_forward_refs()
