# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class WeekRegularity(BaseModel):
    """
    Week Regularity  # noqa: E501
    """
    frequency: StrictInt = Field(description="The frequency of the Week Regularity. For example, a value of 2 indicates every 2 weeks")
    days_of_week: List[StrictStr] = Field(description="Days of the week. One or more of - Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday", alias="daysOfWeek")
    type:  StrictStr = Field(...,alias="type", description="The type of Date Regularity") 
    __properties = ["frequency", "daysOfWeek", "type"]

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""

        # Finbourne removed enum validation on all models except the
        # oneOf-discriminator case: each oneOf variant declares a
        # discriminator field (e.g. `type`, `launcherType`) whose enum has
        # exactly one allowable value, which pydantic uses to route the
        # union. We detect that shape here (single allowable value) — no
        # manual class list, no hard-coded discriminator name.

        _allowed = ['Week']
        if len(_allowed) != 1:
            return value
        if value not in _allowed:
            raise ValueError(f"must be one of enum values {_allowed}")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> WeekRegularity:
        """Create an instance of WeekRegularity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> WeekRegularity:
        """Create an instance of WeekRegularity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return WeekRegularity.parse_obj(obj)

        _obj = WeekRegularity.parse_obj({
            "frequency": obj.get("frequency"),
            "days_of_week": obj.get("daysOfWeek"),
            "type": obj.get("type")
        })
        return _obj

WeekRegularity.update_forward_refs()
