# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class WorkflowRun(BaseModel):
    """
    Information about the run of the Workflow that created this Task, inherited from the root/ultimate parent Task.  # noqa: E501
    """
    id: StrictInt = Field(description="The id of this run of the Workflow. Assigned once, when the run is instantiated.")
    as_at_created: datetime = Field(description="The version.asAtCreated of the root/ultimate parent Task of this run.", alias="asAtCreated")
    completion_status:  StrictStr = Field(...,alias="completionStatus", description="The completion status of the root/ultimate parent Task of this run: NotStarted, InProgress, or Completed.") 
    __properties = ["id", "asAtCreated", "completionStatus"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> WorkflowRun:
        """Create an instance of WorkflowRun from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> WorkflowRun:
        """Create an instance of WorkflowRun from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return WorkflowRun.parse_obj(obj)

        _obj = WorkflowRun.parse_obj({
            "id": obj.get("id"),
            "as_at_created": obj.get("asAtCreated"),
            "completion_status": obj.get("completionStatus")
        })
        return _obj

WorkflowRun.update_forward_refs()
