# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid_workflow.models.perpetual_property import PerpetualProperty
from lusid_workflow.models.resource_id import ResourceId
from lusid_workflow.models.version_info import VersionInfo
from lusid_workflow.models.workflow_structure import WorkflowStructure

class WorkflowResponse(BaseModel):
    """
    A Workflow  # noqa: E501
    """
    id: ResourceId
    version: Optional[VersionInfo] = None
    display_name:  StrictStr = Field(...,alias="displayName", description="Human readable name") 
    description:  Optional[StrictStr] = Field(None,alias="description", description="Human readable description") 
    root_task_definition_id: ResourceId = Field(alias="rootTaskDefinitionId")
    workflow_structure: Optional[WorkflowStructure] = Field(default=None, alias="workflowStructure")
    properties: Optional[Dict[str, PerpetualProperty]] = Field(default=None, description="The properties of the Workflow, keyed by property key.")
    __properties = ["id", "version", "displayName", "description", "rootTaskDefinitionId", "workflowStructure", "properties"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> WorkflowResponse:
        """Create an instance of WorkflowResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of id
        if self.id:
            _dict['id'] = self.id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of version
        if self.version:
            _dict['version'] = self.version.to_dict()
        # override the default output from pydantic by calling `to_dict()` of root_task_definition_id
        if self.root_task_definition_id:
            _dict['rootTaskDefinitionId'] = self.root_task_definition_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of workflow_structure
        if self.workflow_structure:
            _dict['workflowStructure'] = self.workflow_structure.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in properties (dict)
        _field_dict = {}
        if self.properties:
            for _key in self.properties:
                if self.properties[_key]:
                    _field_dict[_key] = self.properties[_key].to_dict()
            _dict['properties'] = _field_dict
        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict['description'] = None

        # set to None if properties (nullable) is None
        # and __fields_set__ contains the field
        if self.properties is None and "properties" in self.__fields_set__:
            _dict['properties'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> WorkflowResponse:
        """Create an instance of WorkflowResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return WorkflowResponse.parse_obj(obj)

        _obj = WorkflowResponse.parse_obj({
            "id": ResourceId.from_dict(obj.get("id")) if obj.get("id") is not None else None,
            "version": VersionInfo.from_dict(obj.get("version")) if obj.get("version") is not None else None,
            "display_name": obj.get("displayName"),
            "description": obj.get("description"),
            "root_task_definition_id": ResourceId.from_dict(obj.get("rootTaskDefinitionId")) if obj.get("rootTaskDefinitionId") is not None else None,
            "workflow_structure": WorkflowStructure.from_dict(obj.get("workflowStructure")) if obj.get("workflowStructure") is not None else None,
            "properties": dict(
                (_k, PerpetualProperty.from_dict(_v))
                for _k, _v in obj.get("properties").items()
            )
            if obj.get("properties") is not None
            else None
        })
        return _obj

WorkflowResponse.update_forward_refs()
