# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid_workflow.models.workflow_structure_edges import WorkflowStructureEdges
from lusid_workflow.models.workflow_structure_nodes import WorkflowStructureNodes

class WorkflowStructure(BaseModel):
    """
    Describes the structure of a Workflow as a graph of Task Definitions  # noqa: E501
    """
    nodes: Optional[WorkflowStructureNodes] = None
    edges: Optional[WorkflowStructureEdges] = None
    __properties = ["nodes", "edges"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> WorkflowStructure:
        """Create an instance of WorkflowStructure from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of nodes
        if self.nodes:
            _dict['nodes'] = self.nodes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of edges
        if self.edges:
            _dict['edges'] = self.edges.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> WorkflowStructure:
        """Create an instance of WorkflowStructure from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return WorkflowStructure.parse_obj(obj)

        _obj = WorkflowStructure.parse_obj({
            "nodes": WorkflowStructureNodes.from_dict(obj.get("nodes")) if obj.get("nodes") is not None else None,
            "edges": WorkflowStructureEdges.from_dict(obj.get("edges")) if obj.get("edges") is not None else None
        })
        return _obj

WorkflowStructure.update_forward_refs()
