# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid_workflow.models.task_definition import TaskDefinition

class WorkflowStructureNodes(BaseModel):
    """
    The nodes of a Workflow structure graph — the Task Definitions involved  # noqa: E501
    """
    task_definitions: Optional[List[TaskDefinition]] = Field(default=None, description="The Task Definitions that make up the nodes of this Workflow", alias="taskDefinitions")
    __properties = ["taskDefinitions"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> WorkflowStructureNodes:
        """Create an instance of WorkflowStructureNodes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in task_definitions (list)
        _items = []
        if self.task_definitions:
            for _item in self.task_definitions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['taskDefinitions'] = _items
        # set to None if task_definitions (nullable) is None
        # and __fields_set__ contains the field
        if self.task_definitions is None and "task_definitions" in self.__fields_set__:
            _dict['taskDefinitions'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> WorkflowStructureNodes:
        """Create an instance of WorkflowStructureNodes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return WorkflowStructureNodes.parse_obj(obj)

        _obj = WorkflowStructureNodes.parse_obj({
            "task_definitions": [TaskDefinition.from_dict(_item) for _item in obj.get("taskDefinitions")] if obj.get("taskDefinitions") is not None else None
        })
        return _obj

WorkflowStructureNodes.update_forward_refs()
