# coding: utf-8

"""
    FINBOURNE Workflow API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid_workflow.models.child_task_definition_edge import ChildTaskDefinitionEdge

class WorkflowStructureEdges(BaseModel):
    """
    The edges of a Workflow structure graph — the parent-child relationships between Task Definitions  # noqa: E501
    """
    child_task_definitions: Optional[List[ChildTaskDefinitionEdge]] = Field(default=None, description="The child Task Definition relationships", alias="childTaskDefinitions")
    __properties = ["childTaskDefinitions"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> WorkflowStructureEdges:
        """Create an instance of WorkflowStructureEdges from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in child_task_definitions (list)
        _items = []
        if self.child_task_definitions:
            for _item in self.child_task_definitions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['childTaskDefinitions'] = _items
        # set to None if child_task_definitions (nullable) is None
        # and __fields_set__ contains the field
        if self.child_task_definitions is None and "child_task_definitions" in self.__fields_set__:
            _dict['childTaskDefinitions'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> WorkflowStructureEdges:
        """Create an instance of WorkflowStructureEdges from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return WorkflowStructureEdges.parse_obj(obj)

        _obj = WorkflowStructureEdges.parse_obj({
            "child_task_definitions": [ChildTaskDefinitionEdge.from_dict(_item) for _item in obj.get("childTaskDefinitions")] if obj.get("childTaskDefinitions") is not None else None
        })
        return _obj

WorkflowStructureEdges.update_forward_refs()
